class BibleData {
  static const List<Map<String, dynamic>> oldTestament = [
    {'name': 'Gênesis', 'abbr': 'GN', 'chapters': 50},
    {'name': 'Êxodo', 'abbr': 'EX', 'chapters': 40},
    {'name': 'Levítico', 'abbr': 'LV', 'chapters': 27},
    {'name': 'Números', 'abbr': 'NM', 'chapters': 36},
    {'name': 'Deuteronômio', 'abbr': 'DT', 'chapters': 34},
    {'name': 'Josué', 'abbr': 'JS', 'chapters': 24},
    {'name': 'Juízes', 'abbr': 'JZ', 'chapters': 21},
    {'name': 'Rute', 'abbr': 'RT', 'chapters': 4},
    {'name': '1 Samuel', 'abbr': '1SAM', 'chapters': 31},
    {'name': '2 Samuel', 'abbr': '2SAM', 'chapters': 24},
    {'name': '1 Reis', 'abbr': '1RS', 'chapters': 22},
    {'name': '2 Reis', 'abbr': '2RS', 'chapters': 25},
    {'name': '1 Crônicas', 'abbr': '1CR', 'chapters': 29},
    {'name': '2 Crônicas', 'abbr': '2CR', 'chapters': 36},
    {'name': 'Esdras', 'abbr': 'ED', 'chapters': 10},
    {'name': 'Neemias', 'abbr': 'NE', 'chapters': 13},
    {'name': 'Ester', 'abbr': 'ET', 'chapters': 10},
    {'name': 'Jó', 'abbr': 'JOB', 'chapters': 42},
    {'name': 'Salmos', 'abbr': 'SL', 'chapters': 150},
    {'name': 'Provérbios', 'abbr': 'PV', 'chapters': 31},
    {'name': 'Eclesiastes', 'abbr': 'EC', 'chapters': 12},
    {'name': 'Cânticos', 'abbr': 'CT', 'chapters': 8},
    {'name': 'Isaías', 'abbr': 'IS', 'chapters': 66},
    {'name': 'Jeremias', 'abbr': 'JR', 'chapters': 52},
    {'name': 'Lamentações', 'abbr': 'LM', 'chapters': 5},
    {'name': 'Ezequiel', 'abbr': 'EZ', 'chapters': 48},
    {'name': 'Daniel', 'abbr': 'DN', 'chapters': 12},
    {'name': 'Oseias', 'abbr': 'OS', 'chapters': 14},
    {'name': 'Joel', 'abbr': 'JL', 'chapters': 3},
    {'name': 'Amós', 'abbr': 'AM', 'chapters': 9},
    {'name': 'Obadias', 'abbr': 'OB', 'chapters': 1},
    {'name': 'Jonas', 'abbr': 'JN', 'chapters': 4},
    {'name': 'Miqueias', 'abbr': 'MQ', 'chapters': 7},
    {'name': 'Naum', 'abbr': 'NA', 'chapters': 3},
    {'name': 'Habacuque', 'abbr': 'HC', 'chapters': 3},
    {'name': 'Sofonias', 'abbr': 'SF', 'chapters': 3},
    {'name': 'Ageu', 'abbr': 'AG', 'chapters': 2},
    {'name': 'Zacarias', 'abbr': 'ZC', 'chapters': 14},
    {'name': 'Malaquias', 'abbr': 'ML', 'chapters': 4},
  ];

  static const List<Map<String, dynamic>> newTestament = [
    {'name': 'Mateus', 'abbr': 'MT', 'chapters': 28},
    {'name': 'Marcos', 'abbr': 'MC', 'chapters': 16},
    {'name': 'Lucas', 'abbr': 'LC', 'chapters': 24},
    {'name': 'João', 'abbr': 'JO', 'chapters': 21},
    {'name': 'Atos', 'abbr': 'AT', 'chapters': 28},
    {'name': 'Romanos', 'abbr': 'RM', 'chapters': 16},
    {'name': '1 Coríntios', 'abbr': '1CO', 'chapters': 16},
    {'name': '2 Coríntios', 'abbr': '2CO', 'chapters': 13},
    {'name': 'Gálatas', 'abbr': 'GL', 'chapters': 6},
    {'name': 'Efésios', 'abbr': 'EF', 'chapters': 6},
    {'name': 'Filipenses', 'abbr': 'FP', 'chapters': 4},
    {'name': 'Colossenses', 'abbr': 'CL', 'chapters': 4},
    {'name': '1 Tessalonicenses', 'abbr': '1TS', 'chapters': 5},
    {'name': '2 Tessalonicenses', 'abbr': '2TS', 'chapters': 3},
    {'name': '1 Timóteo', 'abbr': '1TM', 'chapters': 6},
    {'name': '2 Timóteo', 'abbr': '2TM', 'chapters': 4},
    {'name': 'Tito', 'abbr': 'TT', 'chapters': 3},
    {'name': 'Filemom', 'abbr': 'FM', 'chapters': 1},
    {'name': 'Hebreus', 'abbr': 'HB', 'chapters': 13},
    {'name': 'Tiago', 'abbr': 'TG', 'chapters': 5},
    {'name': '1 Pedro', 'abbr': '1PE', 'chapters': 5},
    {'name': '2 Pedro', 'abbr': '2PE', 'chapters': 3},
    {'name': '1 João', 'abbr': '1JO', 'chapters': 5},
    {'name': '2 João', 'abbr': '2JO', 'chapters': 1},
    {'name': '3 João', 'abbr': '3JO', 'chapters': 1},
    {'name': 'Judas', 'abbr': 'JD', 'chapters': 1},
    {'name': 'Apocalipse', 'abbr': 'AP', 'chapters': 22},
  ];
}
